// Generated by CoffeeScript 1.6.3
(function() {
  var Q, QStep,
    __slice = [].slice;

  Q = require("q");

  QStep = function() {
    var context, fns;
    fns = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    context = this === (function() {
      return this;
    })() ? {} : this;
    return fns.reduceRight(function(next, fn) {
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return Q["try"](function() {
          return fn.apply(context, args);
        }).then(next);
      };
    }, function(x) {
      return x;
    })();
  };

  module.exports = QStep;

}).call(this);
